### ISSUE TITLE
Any plans on releasing version 2.2.6? 

### ISSUE THREAD

**Issue by Not-a-Tyler** [a-bakedpotato/Potato-Launcher#1]
You have 2.2.6 on your [Potato-Launcher-Dist](https://github.com/a-bakedpotato/Potato-Launcher-Dist) but you have not released the code here, this would be much appreciated

**Comment by a-bakedpotato** [comment]
sorry i dont check github often (best way to contact me is via [discord](https://discord.gg/9TVJAht)), i no longer have this code, best id be able to do would be to decompile the dist version. 
however, i started working on a v3, no eta on that yet but you can watch the commits here
